spring:
  application:
    name: eventAPI

  datasource:
    url: jdbc:postgresql://localhost:5422/EventClean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration